"""build_notebooks.py — gera 3 notebooks Colab auto-contidos (código real das etapas + descrições curtas)."""
import os, nbformat as nbf
HERE=os.path.dirname(os.path.abspath(__file__)); ROOT=os.path.join(HERE,".."); OUT=os.path.join(ROOT,"notebooks")
def src(n): return open(os.path.join(HERE,n),encoding="utf-8").read()
def md(t): return nbf.v4.new_markdown_cell(t)
def code(t): return nbf.v4.new_code_cell(t)
def script(nome,desc,extra_run=None):
    cells=[md(desc), code(f"%%writefile /content/ProjetoA_WP1A/src/{nome}\n"+src(nome))]
    if extra_run: cells.append(code(extra_run))
    return cells
SETUP='''import os; os.makedirs("/content/ProjetoA_WP1A/src",exist_ok=True); os.chdir("/content/ProjetoA_WP1A")
os.environ["WP1A_ROOT"]="/content/ProjetoA_WP1A"; os.environ["NJOBS"]="2"
!pip -q install pyreadr pyarrow tabulate 2>/dev/null; print("ambiente pronto")'''
CAB='''# WP1A — Benchmark reproduzível de métodos clássicos de ML no Tennessee Eastman Process
**Disciplina MEI0028/MEI0015 – Modelagem e Simulação · PUC Goiás · 2026 · Prof. Clarimar J. Coelho**

Base: Rieth et al. (2017), Harvard Dataverse, DOI 10.7910/DVN/6C3JR1 (domínio público) — 21 classes, 52 variáveis, 500 execuções/classe.
Protocolo: divisão **por execução (run)**; hiperparâmetros só na validação; teste lido uma única vez; 5 sementes; F1 macro + MCC; custo computacional medido no mesmo hardware.

Estes notebooks reproduzem exatamente o código executado. Cada célula `%%writefile` grava o script numerado; a célula seguinte o executa.
'''
# ---------- NB1: dados, auditoria, divisão, EDA
nb=nbf.v4.new_notebook(); nb.cells=[md(CAB+"\n## Notebook 1 de 3 — Dados, auditoria, divisão por execução e análise exploratória"), md("### 0. Ambiente\nCria a estrutura de pastas do repositório (§20 do WP1A) e instala dependências."), code(SETUP)]
nb.cells+=script("01_download.py","### 1. Download com verificação de integridade\nOs 4 arquivos `.RData` (1,4 GB) vêm do Harvard Dataverse. O servidor recusa o *user-agent* padrão do Python (HTTP 403), por isso usa-se `curl`. O **MD5 de cada arquivo é conferido** contra o publicado na API do repositório: qualquer byte alterado no download invalidaria o arquivo.","!python3 -u src/01_download.py")
nb.cells+=script("convert_rdata.py","### 2. Conversão para Parquet com memória constante\nLer o arquivo de 837 MB com `pyreadr` materializa 9,6 M linhas em R **e** em pandas ao mesmo tempo (> 8 GB) — estourou a memória do Colab (12 GB) e estouraria a de um notebook de 8 GB. Solução: o R grava **uma parte por classe** (`saveRDS`); o Python lê parte a parte e anexa a um único Parquet em `float32` (precisão de ~7 dígitos, suficiente para sensores; metade da memória).","!python3 -u src/convert_rdata.py")
nb.cells+=script("02_auditoria.py","### 3. Auditoria da base (WP1A §9.1)\nResponde, por lotes, aos 8 itens exigidos: linhas/colunas, nomes das variáveis, classes, execuções por classe, amostras por execução, nulos/infinitos, duplicatas, relação entre arquivos. Gera a **Tabela 1** do artigo.","!python3 -u src/02_auditoria.py && cat reports/01-auditoria.md")
nb.cells+=script("03_split.py","### 4. Divisão por execução e manifesto (WP1A §9.3 · entrega A3)\nA **execução completa** (`simulationRun`) é a unidade indivisível: um run vai inteiro para treino, validação ou teste. Treino = 100 runs/classe, validação = 50 (ambos do arquivo *Training*), teste = todos os 500 do *Testing*. A interseção entre conjuntos é verificada programaticamente (por arquivo de origem — o mesmo número de run em *Training* e *Testing* são simulações distintas). O manifesto gerado aqui é **idêntico byte a byte** ao gerado no Mac (mesma semente).","!python3 -u src/03_split.py && md5sum results/metadata/manifesto_divisao.csv")
nb.cells+=script("05_eda.py","### 5. Análise exploratória (WP1A §9.2 · entrega A2)\nSobre o treino apenas: descritivas, correlação, PCA e o afastamento de cada falha em relação ao regime normal (em desvios-padrão do normal). Observação: essa medida capta deslocamentos de **média**; falhas de variância (10, 14, 19) ficam subestimadas.","!python3 -u src/05_eda.py && cat results/metadata/eda_sumario.json")
nb.cells.append(md("### Resultados obtidos nesta etapa (execução de 06/09/2026)\n| Arquivo | Linhas | Classes | Runs/classe | Amostras/run | Nulos | Infinitos | Duplicatas |\n|---|---|---|---|---|---|---|---|\n| FaultFree_Training | 250.000 | 1 | 500 | 500 | 0 | 0 | 0 |\n| FaultFree_Testing | 480.000 | 1 | 500 | 960 | 0 | 0 | 0 |\n| Faulty_Training | 5.000.000 | 20 | 500 | 500 | 0 | 0 | 0 |\n| Faulty_Testing | 9.600.000 | 20 | 500 | 960 | 0 | 0 | 0 |\n\n52 variáveis = 41 `xmeas` + 11 `xmv`, idênticas em treino e teste. PCA: 2 componentes explicam 43,9%; 10 explicam 74,5%. 21 pares com |r| > 0,9. Falhas mais próximas do normal (média): 9, 14, 10, 15, 19; mais distantes: 6, 18, 2, 1."))
nbf.write(nb,os.path.join(OUT,"WP1A_01_dados_auditoria_divisao_eda.ipynb"))
# ---------- NB2: vazamento + hiperparâmetros
nb=nbf.v4.new_notebook(); nb.cells=[md(CAB+"\n## Notebook 2 de 3 — Experimento do vazamento e seleção de hiperparâmetros\n> Pré-requisito: notebook 1 executado (parquets + manifesto em `/content/ProjetoA_WP1A`)."), code(SETUP)]
nb.cells+=script("04_piloto_vazamento.py","### 6. O experimento do vazamento (WP1A §18)\nMesmo modelo, mesmo volume de dados (25 runs/classe), duas condições: **(A)** divisão por execução — o protocolo; **(B)** divisão aleatória por amostra — a prática dominante na literatura, em que leituras vizinhas da mesma simulação caem em treino e teste. A diferença B − A mede o vazamento. Quatro variantes (árvore e floresta, com e sem poda) testam se o efeito cresce com a capacidade de memorização.\n\n**Rótulo físico**: nos runs com falha, as 20 primeiras amostras (1 h) são fisicamente normais — recebem rótulo 0.","!python3 -u src/04_piloto_vazamento.py | tail -6 && cat results/tables/tab_piloto_vazamento.csv")
nb.cells+=script("nystroem_sgd.py","### 7. SVM escalável: Nyström + gradiente estocástico em lotes\nO SVM com núcleo RBF exato custa O(n²)–O(n³) e travou a máquina com 30 mil amostras. `LinearSVC` sobre a matriz densa de Nyström exige ~16 B/elemento (D = 1000 → > 8 GB). Esta classe aproxima o núcleo RBF (Nyström) e treina um SVM linear (perda *hinge*) por `partial_fit` em lotes de 100 mil linhas: memória ≈ lote × D (301 MB medidos).")
nb.cells+=script("06_busca_hp.py","### 8. Busca de hiperparâmetros — só na validação (WP1A §9.5)\nGrade fatorial reduzida, 4 a 12 configurações por modelo (como Koçak et al., 2026). Critério: F1 macro na **validação**. O teste não é lido. `HP_MODELOS` permite dividir a busca entre máquinas: no projeto, o XGBoost rodou aqui (GPU T4) e os demais no Mac — a CPU do Colab é 5–10× mais lenta que um M3 para o scikit-learn, e **os tempos desta etapa não são usados** no artigo.","import os; os.environ[\"HP_MODELOS\"]=\"xgboost\"; os.environ[\"HP_N_TREINO\"]=\"50\"\n!python3 -u src/06_busca_hp.py")
nb.cells.append(md("### Resultados obtidos (06/09/2026)\n**Vazamento (Δ F1 macro, por amostra − por execução):** árvore com folha ≥ 50: +0,012 · árvore sem poda: +0,028 · RF folha ≥ 50: +0,013 · RF sem poda: +0,028. Efeito real, reprodutível e crescente com a capacidade — mas modesto com vetores instantâneos.\n\n**Melhor F1 macro na validação por modelo:** regressão logística 0,4635 (C = 1) · árvore 0,7429 (folha ≥ 20, sem limite de profundidade; `max_depth=20` custou 8 pontos) · XGBoost 0,8135 (lr 0,1, profundidade 6, 500 árvores) · Random Forest, Gradient Boosting e SVM: ver `configs/hiperparametros_escolhidos.json`."))
nbf.write(nb,os.path.join(OUT,"WP1A_02_vazamento_hiperparametros.ipynb"))
# ---------- NB3: treino final + avaliação + registro
nb=nbf.v4.new_notebook(); nb.cells=[md(CAB+"\n## Notebook 3 de 3 — Treino final, avaliação e registro de figuras/tabelas\n> **Os tempos oficiais do artigo foram medidos em um único computador (Apple M3, 8 GB, 4 núcleos, `nice 19`).** Executar aqui reproduz as métricas de acerto, não os tempos."), code(SETUP)]
nb.cells+=script("06b_merge_hp.py","### 9. Congelamento da configuração\nMescla as buscas (Mac + Colab) e escolhe, por modelo, a melhor configuração pelo F1 macro de validação. A partir daqui nada muda antes de o teste ser lido.","!python3 -u src/06b_merge_hp.py")
nb.cells+=script("07_treino_final.py","### 10. Treino final e avaliação no teste (WP1A §9.6 · §10)\nCada (modelo, semente) roda em **subprocesso isolado** para medir o pico de memória por modelo. Treino: 100 runs/classe; teste: os 500 runs/classe do *Testing* (10,08 M amostras), em lotes. Registra tempo de treino, tempo de inferência, tamanho do modelo serializado e pico de memória, além das métricas com rótulo físico (primário) e rótulo do run (secundário). Sementes 42, 123, 2024, 7, 555.","!NJOBS=2 python3 -u src/07_treino_final.py")
nb.cells+=script("08_avaliacao.py","### 11. Avaliação, estatística e figuras (WP1A §10 · §11 · §12)\nMédia ± dp e IC 95% (t, gl = 4) nas 5 sementes; matrizes de confusão agregadas; F1 por classe; pares mais confundidos; Friedman + Wilcoxon pareado com correção de Holm; métricas em nível de execução (voto majoritário, comparável a Koçak et al., 2026); gráficos de F1/MCC, custo e compromisso desempenho × custo.","!python3 -u src/08_avaliacao.py && cat results/tables/tab03_metricas_globais.csv")
nb.cells+=script("09_registro.py","### 12. Registro de figuras e tabelas\nCopia os artefatos relevantes para `apresentacao/` e gera o Excel de referenciamento (ID, arquivo, legenda, descrição, explicação breve, seção do artigo, insumo do WP1A).","!python3 -u src/09_registro.py")
nbf.write(nb,os.path.join(OUT,"WP1A_03_treino_final_avaliacao.ipynb"))
for f in sorted(os.listdir(OUT)): print(f, os.path.getsize(os.path.join(OUT,f))//1024,"KB")
